service: hello-serverless

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  stage: dev
  memorySize: 128
  timeout: 3

functions:
  hello:
    handler: handler.hello
    memorySize: 256
    timeout: 4
    vpc:
      securityGroupIds:
        - sg-8a07c1e4
      subnetIds:
        - subnet-7458830f
        - subnet-480c2f20

  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true

  addBm:
    handler: add-bm.add
    events:
      - http:
          path: math/addBm
          method: post
          integration: lambda
          request:
            template:
              application/json: >
                #set($inputRoot = $input.path('$'))
                {
                  "num1": $inputRoot.input.operand1,
                  "num2": $inputRoot.input.operand2
                }
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
              Content-Type: "'application/json'"
            template: >
              #set($inputRoot = $input.path('$'))
              {
                "result": $inputRoot
              }
